#!/usr/bin/env python3
"""生成 internal/config/settings_catalog_gen.go — 全量扫描 config.Env / os.Getenv 调用点。

一次性工具：扫描 cmd/ internal/ 下所有 .go（排除 _test），提取：
  - config.Env("KEY", "DEFAULT") 双参调用 → key + 默认值
  - os.Getenv("KEY") 单参调用 → key（默认值空）
自动推断：分类（前缀映射）、敏感（KEY/SECRET/PASSWORD/TOKEN/DSN）、
类型（bool/int/float/secret/string）、引导标记（_MYSQL_DSN / 鉴权密钥 / 端口）。
描述取调用点上方最近注释行。输出 Go 源文件。
"""
import re
import sys
from pathlib import Path

ROOT = Path("/Users/junjunyi/src-code/my-geo")

ENV_RE = re.compile(r'(?:config\.Env|os\.Getenv|os\.LookupEnv)\(\s*"([A-Z][A-Z0-9_]+)"\s*(?:,\s*"((?:[^"\\]|\\.)*)")?')
COMMENT_RE = re.compile(r'^\s*(?://|#)\s*(.*)$')

CATEGORY_RULES = [
    ("GEO_AUTH_", "auth"), ("GEO_JWT", "auth"), ("GEO_ALLOW_REGISTER", "auth"),
    ("GEO_BILLING_", "billing"), ("GEO_WXPAY", "billing"), ("GEO_ALIPAY", "billing"),
    ("GEO_STRIPE", "billing"), ("GEO_PAY_", "billing"),
    ("GEO_REDIS", "queue"), ("GEO_QUEUE", "queue"),
    ("GEO_LLM", "llm"),
    ("GEO_OPENAI", "engines"), ("GEO_PERPLEXITY", "engines"), ("GEO_GEMINI", "engines"),
    ("GEO_CLAUDE", "engines"), ("GEO_GROK", "engines"), ("GEO_QWEN", "engines"),
    ("GEO_GLM", "engines"), ("GEO_DEEPSEEK", "engines"), ("GEO_KIMI", "engines"),
    ("GEO_WENXIN", "engines"), ("GEO_DOUBAO", "engines"), ("GEO_XIAOMI", "engines"),
    ("GEO_XUNFEI", "engines"), ("GEO_YUANBAO", "engines"),
    ("GEO_CHINACHECK", "chinacheck"),
    ("GEO_OFFLINE", "offline"),
    ("GEO_HISTORY", "history"),
    ("GEO_ADMIN", "admin"), ("GEO_OPENAPI", "admin"),
    ("GEO_WL", "whitelabel"),
    ("GEO_SMTP", "mail"), ("GEO_MAIL", "mail"),
    ("GEO_MCP", "mcp"),
    ("GEO_DATA", "storage"),
    ("GEO_PORT", "server"), ("GEO_HOST", "server"), ("GEO_RULES", "server"),
    ("GEO_CMS", "server"), ("GEO_PAGE", "server"), ("GEO_CACHE", "server"),
    ("GEO_TEST", "test"),
]

BOOTSTRAP_SUFFIXES = ("_MYSQL_DSN", "_MYSQL_DB")
# 引导变量：必须在 DB 加载前确定（连接/安全边界），DB 不覆盖，管理后台只读。
# GEO_JWT_SECRET：签名密钥，改了会导致所有会话失效，须经环境变量注入。
BOOTSTRAP_KEYS = {"GEO_JWT_SECRET"}

SECRET_MARKERS = ("KEY", "SECRET", "PASSWORD", "TOKEN", "DSN", "CREDENTIAL")

def classify(key: str, default: str):
    cat = "general"
    for prefix, c in CATEGORY_RULES:
        if key.startswith(prefix):
            cat = c
            break
    is_secret = any(m in key for m in SECRET_MARKERS)
    is_bootstrap = key.endswith(BOOTSTRAP_SUFFIXES) or key in BOOTSTRAP_KEYS
    typ = "string"
    if key in BOOTSTRAP_KEYS or is_secret:
        typ = "secret"
    elif default.lower() in ("true", "false", "1", "0", "yes", "no"):
        typ = "bool"
    elif re.fullmatch(r"-?\d+", default.strip()):
        typ = "int"
    elif re.fullmatch(r"-?\d+(\.\d+)?", default.strip()):
        typ = "float"
    return cat, typ, is_secret, is_bootstrap

def extract():
    found = {}
    for f in sorted((ROOT / "internal").rglob("*.go")) + sorted((ROOT / "cmd").rglob("*.go")):
        if "_test.go" in f.name or "settings_catalog" in f.name:
            continue
        try:
            lines = f.read_text(encoding="utf-8").splitlines()
        except Exception:
            continue
        for i, line in enumerate(lines):
            for m in ENV_RE.finditer(line):
                key, default = m.group(1), (m.group(2) or "").replace("\\\"", '"')
                if not key.startswith("GEO_"):
                    continue
                desc = ""
                # 向上找最近的注释行（最多 4 行）
                for j in range(i - 1, max(-1, i - 5), -1):
                    cm = COMMENT_RE.match(lines[j])
                    if cm:
                        desc = cm.group(1).strip()
                        if desc:
                            break
                    if lines[j].strip() and not lines[j].strip().startswith(("//", "#")):
                        break
                rec = found.setdefault(key, {"default": default, "desc": desc})
                if not rec["default"] and default:
                    rec["default"] = default
                if not rec["desc"] and desc:
                    rec["desc"] = desc
    return found

def render(found):
    keys = sorted(found)
    lines = []
    lines.append("// Code generated by scripts/gen_settings_catalog.py; DO NOT EDIT manually.")
    lines.append("// 扫描范围：internal/ cmd/ 下全部 config.Env / os.Getenv 调用点。")
    lines.append("// 覆盖所有 GEO_* 变量；描述/分类为自动推断，可在 settings_catalog.go 中手工覆盖。")
    lines.append("package config")
    lines.append("")
    lines.append("func buildCatalog() []Setting {")
    lines.append("\treturn []Setting{")
    for k in keys:
        rec = found[k]
        default = rec["default"]
        desc = rec["desc"].replace("\\", "\\\\").replace('"', '\\"')
        cat, typ, sec, boot = classify(k, default)
        lines.append(f'\t\t{{Key: "{k}", DefaultValue: "{default}", Description: "{desc}", Category: "{cat}", Type: "{typ}", IsSecret: {str(sec).lower()}, IsBootstrap: {str(boot).lower()}}},')
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"

def main():
    found = extract()
    out = render(found)
    dst = ROOT / "internal/config/settings_catalog_gen.go"
    dst.write_text(out, encoding="utf-8")
    print(f"OK: {len(found)} 个变量 -> {dst}")

if __name__ == "__main__":
    main()
